export const UPDATE_ORGANIZATIONS = 'UPDATE_ORGANIZATIONS'
export const UPDATE_SINGLE_ORGANIZATION = 'UPDATE_SINGLE_ORGANIZATION'
export const SET_SELECTED_ORG_PERMISSIONS = 'SET_SELECTED_ORG_PERMISSIONS'
export const SET_SPLASH_PAGES = 'SET_SPlASH_PAGES'
