export const merakiTemplates = (state) => state.merakiTemplates
export const merakiTemplatesCount = (state) => state.merakiTemplatesCount
export const trafficShapingApplicationCategories = (state) => state.trafficShapingApplicationCategories
export const trafficShapingDscpTags = (state) => state.trafficShapingDscpTags
export const contentFilteringCategories = (state) => state.contentFilteringCategories
export const defaultContentFilteringCategories = (state) => state.defaultContentFilteringCategories
export const l7ApplicationCategories = (state) => state.l7ApplicationCategories
export const merakiNetworkCreationFlows = (state) => state.merakiNetworkCreationFlows
export const merakiNetworkCreationFlowsCount = (state) => state.merakiNetworkCreationFlowsCount
export const merakiNetworkCreationSteps = (state) => state.merakiNetworkCreationSteps
export const merakiSecurityComplianceRuleSets = (state) => state.merakiSecurityComplianceRuleSets
export const merakiSecurityComplianceRuleSetsCount = (state) => state.merakiSecurityComplianceRuleSetsCount
export const merakiNameComplianceRuleSets = (state) => state.merakiNameComplianceRuleSets
export const merakiNameComplianceRuleSetsCount = (state) => state.merakiNameComplianceRuleSetsCount
export const merakiNameComplianceChecks = (state) => state.merakiNameComplianceChecks
export const merakiNameComplianceChecksCount = (state) => state.merakiNameComplianceChecksCount
export const merakiConfigurationComplianceRuleSets = (state) => state.merakiConfigurationComplianceRuleSets
export const merakiConfigurationComplianceRuleSetsCount = (state) => state.merakiConfigurationComplianceRuleSetsCount
export const merakiConfigurationComplianceChecks = (state) => state.merakiConfigurationComplianceChecks
export const merakiConfigurationComplianceChecksCount = (state) => state.merakiConfigurationComplianceChecksCount
export const merakiTags = (state) => state.merakiTags
export const merakiTagFilter = (state) => state.merakiTagFilter
export const merakiTaggableResourcesForATag = (state) => state.merakiTaggableResourcesForATag
export const merakiTaggableResources = (state) => state.merakiTaggableResources
export const merakiTaggableResourcesFilter = (state) => state.merakiTaggableResourcesFilter
export const merakiNetworkBases = (state) => state.merakiNetworkBases
export const merakiNetworkBasesCount = (state) => state.merakiNetworkBasesCount
export const merakiClients = (state) => state.merakiClients
export const merakiClientsCount = (state) => state.merakiClientsCount
export const merakiClientEvents = (state) => state.merakiClientEvents
export const merakiClientEventsCount = (state) => state.merakiClientEventsCount
export const merakiClientTrafficHistory = (state) => state.merakiClientTrafficHistory
export const merakiClientTrafficHistoryCount = (state) => state.merakiClientTrafficHistoryCount
export const merakiClientUsageHistory = (state) => state.merakiClientUsageHistory
export const merakiClientUsageHistoryCount = (state) => state.merakiClientUsageHistoryCount
export const merakiClientLatencyHistory = (state) => state.merakiClientLatencyHistory
export const merakiClientLatencyHistoryCount = (state) => state.merakiClientLatencyHistoryCount
export const merakiMonitoringDevices = (state) => state.merakiMonitoringDevices
export const merakiMonitoringDevicesCount = (state) => state.merakiMonitoringDevicesCount
export const merakiDeviceConnectionHistory = (state) => state.merakiDeviceConnectionHistory
export const merakiDeviceConnectionHistoryCount = (state) => state.merakiDeviceConnectionHistoryCount
export const merakiDeviceLatencyHistory = (state) => state.merakiDeviceLatencyHistory
export const merakiDeviceLatencyHistoryCount = (state) => state.merakiDeviceLatencyHistoryCount
export const merakiMonitoringSwitchPorts = (state) => state.merakiMonitoringSwitchPorts
export const merakiMonitoringSwitchPortsCount = (state) => state.merakiMonitoringSwitchPortsCount
export const merakiMonitoringSwitchPortsNetworks = (state) => state.merakiMonitoringSwitchPortsNetworks
export const merakiMonitoringSwitchPortsNetworksCount = (state) => state.merakiMonitoringSwitchPortsNetworksCount
export const merakiMonitoringSwitchPortsDevices = (state) => state.merakiMonitoringSwitchPortsDevices
export const merakiMonitoringSwitchPortsDevicesCount = (state) => state.merakiMonitoringSwitchPortsDevicesCount
export const associatedDevices = (state) => state.associatedDevices
export const associatedDevicesCount = (state) => state.associatedDevicesCount
export const dashboardEntities = (state) => state.dashboardEntities
export const dashboards = (state) => state.dashboards
export const dashboardsCount = (state) => state.dashboardsCount
export const dashboardParameterOptions = (state) => state.dashboardParameterOptions
export const userDashboards = (state) => state.userDashboards
